// zig_runner_build.zig — Shared build.zig generation helpers
// Contains sanitization, emit helpers, and @cImport file generation.

const std = @import("std");
const cache = @import("../cache.zig");

/// Sanitize a C header filename into a valid Zig identifier.
/// Returns the sanitized stem as a slice into the returned buffer.
/// e.g. "vk_mem_alloc.h" → "vk_mem_alloc"
pub const StemResult = struct {
    buf: [64]u8,
    len: usize,

    pub fn slice(self: *const StemResult) []const u8 {
        return self.buf[0..self.len];
    }
};

pub fn sanitizeHeaderStem(hdr: []const u8) StemResult {
    const base = std.fs.path.basename(hdr);
    const stem = if (std.mem.lastIndexOfScalar(u8, base, '.')) |dot|
        base[0..dot]
    else
        base;
    var result = StemResult{ .buf = undefined, .len = @min(stem.len, 63) };
    for (0..result.len) |i| {
        result.buf[i] = if (std.ascii.isAlphanumeric(stem[i])) stem[i] else '_';
    }
    return result;
}

/// Format and append to a buffer in one step.
/// Replaces the repeated allocPrint + defer free + appendSlice pattern.
pub fn appendFmt(
    buf: *std.ArrayListUnmanaged(u8),
    allocator: std.mem.Allocator,
    comptime fmt: []const u8,
    args: anytype,
) !void {
    const chunk = try std.fmt.allocPrint(allocator, fmt, args);
    defer allocator.free(chunk);
    try buf.appendSlice(allocator, chunk);
}

/// Emit linkSystemLibrary + linkLibC calls for a Step.Compile artifact.
pub fn emitLinkLibs(
    buf: *std.ArrayListUnmanaged(u8),
    allocator: std.mem.Allocator,
    link_libs: []const []const u8,
    artifact_name: []const u8,
) !void {
    if (link_libs.len == 0) return;
    for (link_libs) |lib_name| {
        try appendFmt(buf, allocator,
            \\    {s}.linkSystemLibrary("{s}");
            \\
        , .{ artifact_name, lib_name });
    }
    try appendFmt(buf, allocator,
        \\    {s}.linkLibC();
        \\
    , .{artifact_name});
}

/// Emit addIncludePath for a Step.Compile artifact so module-relative headers resolve.
pub fn emitIncludePath(
    buf: *std.ArrayListUnmanaged(u8),
    allocator: std.mem.Allocator,
    source_dir: []const u8,
    artifact_name: []const u8,
) !void {
    try appendFmt(buf, allocator,
        \\    {s}.root_module.addIncludePath(.{{ .cwd_relative = "{s}" }});
        \\
    , .{ artifact_name, source_dir });
}

/// Generate shared @cImport wrapper .zig files for all unique C include headers.
/// Each file is written to the generated cache dir as _{stem}_c.zig and exposes:
///   pub const c = @cImport({ @cInclude("header.h"); });
/// Sidecars use: const c = @import("{stem}_c").c;
/// Note: `usingnamespace` was removed from file scope in Zig 0.15; callers access
/// the cImport result via the `.c` field on the imported module.
pub fn generateSharedCImportFiles(allocator: std.mem.Allocator, targets: anytype) !void {
    var seen = std.StringHashMapUnmanaged(void){};
    defer seen.deinit(allocator);

    for (targets) |*t| {
        for (t.c_includes) |hdr| {
            if (seen.contains(hdr)) continue;
            try seen.put(allocator, hdr, {});

            const stem_result = sanitizeHeaderStem(hdr);
            const safe_stem = stem_result.slice();

            // Generate wrapper content.
            // Callers use: const c = @import("{stem}_c").c;
            // `usingnamespace` was removed from file scope in Zig 0.15 — callers must
            // access the cImport result via the `.c` field on the imported module.
            const wrapper_content = try std.fmt.allocPrint(allocator,
                \\// Shared @cImport wrapper for {s}
                \\// Auto-generated by orhon compiler — do not edit.
                \\// Usage in sidecars: const c = @import("{s}_c").c;
                \\pub const c = @cImport({{
                \\    @cInclude("{s}");
                \\}});
                \\
            , .{ hdr, safe_stem, hdr });
            defer allocator.free(wrapper_content);

            // Write to cache as _{stem}_c.zig
            const file_stem = try std.fmt.allocPrint(allocator, "_{s}_c", .{safe_stem});
            defer allocator.free(file_stem);
            try cache.writeGeneratedZig(file_stem, wrapper_content, allocator);
        }
    }
}

/// Emit addCSourceFiles + linkLibCpp calls for a Step.Compile artifact.
pub fn emitCSourceFiles(
    buf: *std.ArrayListUnmanaged(u8),
    allocator: std.mem.Allocator,
    c_source_files: []const []const u8,
    needs_cpp: bool,
    artifact_name: []const u8,
) !void {
    if (c_source_files.len == 0 and !needs_cpp) return;

    var has_cpp = needs_cpp;
    for (c_source_files) |src_file| {
        // Determine flags: .cpp/.cc files get -std=c++17
        const is_cpp = std.mem.endsWith(u8, src_file, ".cpp") or std.mem.endsWith(u8, src_file, ".cc");
        if (is_cpp) has_cpp = true;
        const flags = if (is_cpp) "\"-std=c++17\"" else "";
        if (is_cpp) {
            try appendFmt(buf, allocator,
                \\    {s}.root_module.addCSourceFiles(.{{
                \\        .files = &.{{"{s}"}},
                \\        .flags = &.{{{s}}},
                \\    }});
                \\
            , .{ artifact_name, src_file, flags });
        } else {
            try appendFmt(buf, allocator,
                \\    {s}.root_module.addCSourceFiles(.{{
                \\        .files = &.{{"{s}"}},
                \\        .flags = &.{{}},
                \\    }});
                \\
            , .{ artifact_name, src_file });
        }
    }

    if (has_cpp) {
        try appendFmt(buf, allocator,
            \\    {s}.linkLibCpp();
            \\
        , .{artifact_name});
    }
}

